name: javamaker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^6.1.1
  path_provider: ^2.1.2
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
flutter:
  uses-material-design: true
flutter_icons:
  linux: true
  image_path: "/linux/icons/avamaker.png"